/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppIncidentsRouteImport } from './routes/app/incidents'
import { Route as AppServersRouteImport } from './routes/app/servers'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppServersServerIdRouteImport } from './routes/app/servers_/$serverId'
import { Route as AppServersServerIdMonitorsMonitorIdRouteImport } from './routes/app/servers_/$serverId_/monitors/$monitorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppServersServerIdRoute = AppServersServerIdRouteImport.update({
  id: '/servers_/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppServersServerIdMonitorsMonitorIdRoute =
  AppServersServerIdMonitorsMonitorIdRouteImport.update({
    id: '/servers_/$serverId_/monitors/$monitorId',
    path: '/servers/$serverId/monitors/$monitorId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/two-factor': typeof TwoFactorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/servers': typeof AppServersRoute
  '/app/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/servers/$serverId': typeof AppServersServerIdRoute
  '/app/servers/$serverId/monitors/$monitorId': typeof AppServersServerIdMonitorsMonitorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/two-factor': typeof TwoFactorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/servers': typeof AppServersRoute
  '/app/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/servers/$serverId': typeof AppServersServerIdRoute
  '/app/servers/$serverId/monitors/$monitorId': typeof AppServersServerIdMonitorsMonitorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/two-factor': typeof TwoFactorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/servers': typeof AppServersRoute
  '/app/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/servers_/$serverId': typeof AppServersServerIdRoute
  '/app/servers_/$serverId_/monitors/$monitorId': typeof AppServersServerIdMonitorsMonitorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/two-factor'
    | '/app/dashboard'
    | '/app/incidents'
    | '/app/servers'
    | '/app/settings'
    | '/oauth/callback'
    | '/app/admin/users'
    | '/app/servers/$serverId'
    | '/app/servers/$serverId/monitors/$monitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/two-factor'
    | '/app/dashboard'
    | '/app/incidents'
    | '/app/servers'
    | '/app/settings'
    | '/oauth/callback'
    | '/app/admin/users'
    | '/app/servers/$serverId'
    | '/app/servers/$serverId/monitors/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/two-factor'
    | '/app/dashboard'
    | '/app/incidents'
    | '/app/servers'
    | '/app/settings'
    | '/oauth/callback'
    | '/app/admin/users'
    | '/app/servers_/$serverId'
    | '/app/servers_/$serverId_/monitors/$monitorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TwoFactorRoute: typeof TwoFactorRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servers': {
      id: '/app/servers'
      path: '/servers'
      fullPath: '/app/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servers_/$serverId': {
      id: '/app/servers_/$serverId'
      path: '/servers/$serverId'
      fullPath: '/app/servers/$serverId'
      preLoaderRoute: typeof AppServersServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servers_/$serverId_/monitors/$monitorId': {
      id: '/app/servers_/$serverId_/monitors/$monitorId'
      path: '/servers/$serverId/monitors/$monitorId'
      fullPath: '/app/servers/$serverId/monitors/$monitorId'
      preLoaderRoute: typeof AppServersServerIdMonitorsMonitorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppServersServerIdRoute: typeof AppServersServerIdRoute
  AppServersServerIdMonitorsMonitorIdRoute: typeof AppServersServerIdMonitorsMonitorIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppServersServerIdRoute: AppServersServerIdRoute,
  AppServersServerIdMonitorsMonitorIdRoute:
    AppServersServerIdMonitorsMonitorIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TwoFactorRoute: TwoFactorRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
